replicasCount: 1
maxUnavailableCount: 0

image:
  repository: gcr.io/videocoin-network/splitter
  tag: latest
  pullPolicy: Always

config: {}

service:
  type: ClusterIP
  externalRpcPort: 5103
  internalRpcPort: 5103

autoscaler:
  minCount: 1
  maxCount: 10
  targets:
    targetCPUUtilizationPercentage: 70

secrets:
  secret: ""
  sentryDsn: ""
